error: add the errno type
Add a type for the kernel's error values.
Can't constrain it too much via the type
system because system calls can return
pretty much anything due to LSMs, seccomp
and FUSE. Even the man pages are famously
incomplete.